version: "3.9"
services:
  api:
    build:
      context: api
    ports:
      - "${API_PORT:-3001}:80"
    networks:
      - localsearch
  ui:
    build:
      context: ui
    ports:
      - "${UI_PORT:-3000}:80"
    environment:
      - API_URL=http://localhost:3001/
    depends_on:
      - api
    networks:
      - localsearch
networks:
  localsearch:
    driver: bridge
