version: "3.9"
services:
  api:
    command: sh -c "npm install && npm run start:debug"
    volumes:
      - ./api:/app
    ports:
      - "${API_DEBUG_PORT:-9229}:9229"
    environment:
      - SWAGGER_ACTIVE=true
  ui:
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./ui:/app
    ports:
      - "${UI_DEBUG_PORT:-9230}:9230"
