# build
FROM node:16-alpine AS builder

WORKDIR /app

COPY . .

RUN npm install
RUN npm run export

# app
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/out /usr/share/nginx/html

ENV PORT=80
EXPOSE ${PORT}

CMD [ "nginx", "-g", "daemon off;" ]